# .github/workflows/daily_commit.yml

name: Daily Automated Commit

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }} 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run daily commit script
      run: python daily_commit.py
      env:
        GIT_USERNAME: TKWebSE
        GIT_USEREMAIL: writetechcode@yahoo.co.jp
